updating auth
machine-learning-apps/ml-template-azure pull request #4
Opened 2020-04-30 18:10 UTC by buchananwp

parsing the info & adding images/explanations

2020-05-01 11:09 UTC, marvinbuss requested changes

2020-05-01 11:09 UTC, marvinbuss commented on .cloud/.azure/workspace.json
> +    "resource_group": "wibuchan",
@buchananwp We should not put your workspace details in the template. Can you please change it back to the placeholders?

2020-05-01 11:09 UTC, marvinbuss commented on .autogit/autogit.json
> +}
What is this file for? I think we should not include this in the template repository. Would be great to understand how this helps the user.

2020-05-01 11:09 UTC, marvinbuss commented on README.md
Thanks for the details. That helps users a lot. Good job!
This is great. Thanks!

2020-05-01 11:11 UTC, marvinbuss commented
@buchananwp Great job. Many thanks for the details and additions. This is great! 👍 

Could you please comment on the issues above?

2020-05-02 00:49 UTC, will-iamalpine reviewed
reset workspace.json and removed autogit artifacts

2020-05-03 12:00 UTC, marvinbuss approved these changes

2020-05-11 07:29 UTC, marvinbuss requested changes
Please just fix the 2 typos and then I will merge. Thanks for the great wok!

2020-05-11 07:29 UTC, marvinbuss commented on README.md
> +You can also delete the `name` parameter, if you want the action to use the defau
Typo: "defau" --> default

2020-05-11 07:29 UTC, marvinbuss commented on README.md
> +    "create_workspace": true
Please fix the indentation.

2020-05-11 16:04 UTC, buchananwp commented on README.md
> +You can also delete the `name` parameter, if you want the action to use the defau
done

2020-05-11 16:04 UTC, buchananwp commented on README.md
> +    "create_workspace": true
done

2020-05-11 16:05 UTC, buchananwp commented
@marvinbuss please review

2020-05-18 14:12 UTC, awmatheson requested changes
The changes are great! We should merge this in once the images are changed and it's brought up to date with master.

2020-05-18 14:12 UTC, awmatheson commented on README.md
> +  <img src="/docs/images/workspace-permissions.png" alt="Workspace Permissions" width="550"/>
For consistency, could we update the images to make them styled similar to the `docs/images/secrets.png` where the sensitive info is blurred and the callout is shown with a red rectangle.

2020-05-18 14:12 UTC, awmatheson commented on README.md
> +  <img src="/docs/images/workspace-overview.png" alt="Workspace Overview" width="550"/>
For consistency, could we update the images to make them styled similar to the `docs/images/secrets.png` where the sensitive info is blurred and the callout is shown with a red rectangle.

2020-09-27 11:31 UTC, closed without merging